"""Message and ContentBlock types."""

import json as _json
from enum import StrEnum
from typing import Any

from pydantic import BaseModel, Field, model_validator

from evoagent.core.ids import generate_id
from evoagent.core.time import utc_now_iso


class MessageRole(StrEnum):
    SYSTEM = "system"
    USER = "user"
    ASSISTANT = "assistant"
    TOOL = "tool"


class ContentBlockType(StrEnum):
    TEXT = "text"
    JSON = "json"
    CODE = "code"
    ERROR = "error"


class ContentBlock(BaseModel):
    """A typed content block within a message."""

    type: ContentBlockType = Field(default=ContentBlockType.TEXT)
    content: str = Field(default="")
    metadata: dict[str, Any] = Field(default_factory=dict)


class ToolCall(BaseModel):
    """A tool call generated by an LLM assistant message.

    Supports both internal format {id, name, arguments}
    and provider wire format {id, type, function: {name, arguments}}.
    """

    id: str = Field(default_factory=lambda: generate_id("call"))
    name: str = Field(default="")
    arguments: dict[str, Any] = Field(default_factory=dict)
    raw: str = Field(default="")
    metadata: dict[str, Any] = Field(default_factory=dict)

    @model_validator(mode="before")
    @classmethod
    def normalize_provider_tool_call(cls, value: Any) -> Any:
        """Normalize provider wire-format tool call to internal format.

        Provider format: {"id": "...", "type": "function", "function": {"name": "...", "arguments": "..."}}
        Internal format: {"id": "...", "name": "...", "arguments": {...}}
        """
        if not isinstance(value, dict):
            return value
        # Already internal format
        if "name" in value and "function" not in value:
            return value
        # Provider wire format
        func = value.get("function")
        if not isinstance(func, dict):
            return value
        raw_args = func.get("arguments", "{}")
        if isinstance(raw_args, str):
            try:
                args = _json.loads(raw_args)
            except _json.JSONDecodeError:
                args = {}
        elif isinstance(raw_args, dict):
            args = raw_args
            raw_args = _json.dumps(raw_args)
        else:
            args = {}
        return {
            "id": value.get("id", ""),
            "name": func.get("name", ""),
            "arguments": args,
            "raw": raw_args if isinstance(raw_args, str) else _json.dumps(raw_args),
            "metadata": {
                "provider_type": value.get("type"),
                "provider_index": value.get("index"),
            },
        }


class Message(BaseModel):
    """A chat message in the agent conversation history.

    Assistant messages may carry tool_calls; tool messages
    reference a tool_call_id. reasoning_content stores
    provider-specific thinking tokens (DeepSeek).
    """

    role: MessageRole = Field(..., description="Message role.")
    content: str = Field(default="", description="Message text content.")
    name: str | None = Field(default=None, description="Optional sender name.")
    tool_call_id: str | None = Field(default=None, description="For tool messages: the ID of the tool call this responds to.")
    tool_calls: list[ToolCall] | None = Field(default=None, description="For assistant messages: tool calls generated by the LLM.")
    reasoning_content: str | None = Field(default=None, description="Provider thinking tokens (DeepSeek). Not shown in CLI.")
    metadata: dict[str, Any] = Field(default_factory=dict)
    created_at: str = Field(default_factory=utc_now_iso)
